### ISSUE TITLE
Add permission in Lambda function handler and role

### ISSUE THREAD

**Issue by davidfrothin** [johnmccuk/cloudflare-ip-security-group-update#1]
Thanks for your contribution

"Effect": "Allow",
            "Action": [
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:DescribeSecurityGroups"
            ],
            "Resource": [
                "*"
            ]

Was needed with "ec2:DescribeSecurityGroups" and it was not mentioned in https://blog.john-mccracken.com/automate-aws-security-group-with-cloudflare-ips-2/ " Lambda function handler and role" section

**Comment by johnmccuk** [comment]
Hi David,

I've updated the post with the change.

Many Thanks
